apiVersion: apps/v1
kind: Deployment
metadata:
  name: '${serviceName}'
  labels:
    app: '${serviceName}'
spec:
  replicas: '${podReplica}'
  selector:
    matchLabels:
      app: '${serviceName}'
  template:
    metadata:
      labels:
        app: '${serviceName}'
    spec:
      containers:
      - name: '${serviceName}'
        image: '${imageRepo}/${serviceName}:${versionTag}'
        envFrom:
        - secretRef:
            name: '${serviceName}-${env}-secret'
